version: '3.8'

services:
  # Laravel Backend API
  backend:
    build: .
    container_name: capstone_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=database
      - DB_DATABASE=capstone_db
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - database
    networks:
      - capstone_network

  # Flutter Web Frontend
  frontend:
    image: cirrusci/flutter:stable
    container_name: capstone_frontend
    ports:
      - "3000:3000"
    volumes:
      - ../flutter_frontend:/app
    working_dir: /app
    command: flutter run -d web-server --web-hostname 0.0.0.0 --web-port 3000
    networks:
      - capstone_network

  # Database
  database:
    image: mysql:8.0
    container_name: capstone_database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: capstone_db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - capstone_network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: capstone_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - capstone_network

volumes:
  mysql_data:

networks:
  capstone_network:
    driver: bridge
